In [4]:
import pandas as pd
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
data = {"name":["a", "b", "c"], "mark": [1,2,3]}
df = pd.DataFrame(data)
df

  name  mark
0    a     1
1    b     2
2    c     3

In [5]:
import pandas as pd
# Sample data
data = {
    "id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["John Doe", "Mary Smith", "Alex Johnson", "Bob Lee", "Eve Adams", 
             "Linda Perez", "Tom Harris", "Sara Khan", "Chris Brown", "Nina Patel"],
    "department": ["IT", "Finance", "HR", "IT", "Marketing", 
                   "Finance", "Sales", "IT", "HR", "Marketing"],
    "gender": ["M", "F", "M", "M", "F", "F", "M", "F", "M", "F"],
    "salary": [85000, 95000, 70000, 80000, 78000, 91000, 67000, 88000, 72000, 76000],
    "joining_date": ["2020-06-15", "2019-08-10", "2021-02-01", "2022-03-20",
                     "2020-11-05", "2018-12-25", "2021-09-10", "2019-04-18",
                     "2022-05-25", "2020-02-12"],
    "performance_score": [4.3, 4.8, 3.9, 4.1, 4.6, 4.9, 3.7, 4.2, 3.8, 4.4],
    "is_active": [True, True, False, True, True, True, True, False, True, True]
}

df = pd.DataFrame(data)
cvs_path = "employee.csv"
excel_path = "employee.xlsx"

df.to_csv( cvs_path, index=False)
df.to_excel(excel_path, index=False, sheet_name="Employee")

In [4]:
! pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [12]:
import pandas as pd
df = pd.read_csv("employee.csv")
df.tail(10)

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [11]:
df.describe()

             id        salary  performance_score
count  10.00000     10.000000          10.000000
mean    5.50000  80200.000000           4.270000
std     3.02765   9354.737362           0.411096
min     1.00000  67000.000000           3.700000
25%     3.25000  73000.000000           3.950000
50%     5.50000  79000.000000           4.250000
75%     7.75000  87250.000000           4.550000
max    10.00000  95000.000000           4.900000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     object
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     int64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     float64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 698.0+ bytes

In [27]:
df["id"]

KeyError: 'id'

In [17]:
type(df["id"])

pandas.core.series.Series

In [19]:
df[["id", "name"]]

   id          name
0   1      John Doe
1   2    Mary Smith
2   3  Alex Johnson
3   4       Bob Lee
4   5     Eve Adams
5   6   Linda Perez
6   7    Tom Harris
7   8     Sara Khan
8   9   Chris Brown
9  10    Nina Patel

In [20]:
df.iloc[0]

id                            1
name                   John Doe
department                   IT
gender                        M
salary                    85000
joining_date         2020-06-15
performance_score           4.3
is_active                  True
Name: 0, dtype: object

# q. "Find all employees whose salary is greater than 80,000."

In [37]:
import pandas as pd
df = pd.read_csv("Employee.csv")
df2 =df[df["salary"] > 80000]
df2

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

In [41]:
df3 = df[df["department"] == "IT"]
df3

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

In [42]:
df4 = df[df["gender"] == "F"]
df4

,id,name,department,gender,salary,joining_date,performance_score,is_active
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

## Q Find IT employees whose salary is greater than 80,000.

In [49]:
df3 = df[((df["department"] == "IT") | (df["department"] == "Finance")) & (df["salary"] > 80000)]
df3

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

## Find employees from IT, HR, or Finance.

In [51]:
df2 = df[(df["department"] == "IT") | 
         (df["department"] == "HR") | 
         (df["department"] == "Finance")]
df2

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True

In [54]:
## using isin 


new=df[df["department"].isin(["IT", "HR", "Finance"])]
new

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True

## 4. loc[] — next important concept

In [55]:
new = df.loc[df["salary"] > 80000]
new

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

In [56]:
new = df[df["salary"] > 80000] 
new

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

In [57]:
new=df.loc[df["salary"] > 80000] 
new

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

In [59]:
new = df.loc[df["salary"] > 80000, ['name', 'salary', 'department']]
new

          name  salary department
0     John Doe   85000         IT
1   Mary Smith   95000    Finance
5  Linda Perez   91000    Finance
7    Sara Khan   88000         IT

## 5. iloc[] 
for integer position

In [ ]:
## rows
df.iloc[0:4]

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True

In [66]:
## rows and column
df.iloc[0:, 1:]

,name,department,gender,salary,joining_date,performance_score,is_active
0,John Doe,IT,M,85000,2020-06-15,4.3,True
1,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

## Q. Find the names of female employees working in the Finance department.

In [80]:
new = df.loc[(df["department"] == "Finance") & (df["gender"] == "F") , ["name", "department"]]
new

          name department
1   Mary Smith    Finance
5  Linda Perez    Finance

In [95]:
# df2=df.loc[(df["department"] == "Finance") & (df["gender"]=="F"),["name", "Gender"]]
import pandas as pd
df = pd.read_csv("Employee.csv")
# print(df)
new = df.loc[(df["department"] == "IT") & (df["gender"] == "M"), ["name", "department"]] 
new

       name department
0  John Doe         IT
3   Bob Lee         IT

## 1. What is sort_values()?

In [105]:
import pandas as pd 
df = pd.read_csv("Employee.csv")
df[["name", "salary"]]
df.sort_values("salary", ascending= False)[["department", "salary"]]

  department  salary
1    Finance   95000
5    Finance   91000
7         IT   88000
0         IT   85000
3         IT   80000
4  Marketing   78000
9  Marketing   76000
8         HR   72000
2         HR   70000
6      Sales   67000

## Sorting

In [104]:
df = pd.read_csv("Employee.csv")
df.sort_values("salary", ascending= False)[["name", "salary"]]
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [103]:
df.sort_values(["salary", "department"])

,id,name,department,gender,salary,joining_date,performance_score,is_active
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True

In [108]:
df.sort_values(["department", "salary"], ascending=[True, False])[["department", "salary", "name"]]

  department  salary          name
1    Finance   95000    Mary Smith
5    Finance   91000   Linda Perez
8         HR   72000   Chris Brown
2         HR   70000  Alex Johnson
7         IT   88000     Sara Khan
0         IT   85000      John Doe
3         IT   80000       Bob Lee
4  Marketing   78000     Eve Adams
9  Marketing   76000    Nina Patel
6      Sales   67000    Tom Harris

## Q1. Sort employees by performance_score, highest first.

Q2. Show only name, department, and salary, sorted by salary highest first.

Q3. Sort by gender and then by salary highest first.

In [109]:
import pandas as pd
df = pd.read_csv("Employee.csv")
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [112]:
df.sort_values("performance_score", ascending=False)
df.sort_values("salary", ascending=False)[["name", "department","salary"]]
df.sort_values(["gender", "salary"], ascending=[False, False])

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

## groupby()

Read this from left to right:

df
 ↓
group rows by department
 ↓
take salary
 ↓
calculate mean


df.groupby("COLUMN")["COLUMN_TO_CALCULATE"].AGGREGATION()

In [114]:
## What is the average salary of each department?

df.groupby("department")["salary"].mean()

department
Finance      93000.000000
HR           71000.000000
IT           84333.333333
Marketing    77000.000000
Sales        67000.000000
Name: salary, dtype: float64

In [115]:
df.groupby("department")["salary"].max()

department
Finance      95000
HR           72000
IT           88000
Marketing    78000
Sales        67000
Name: salary, dtype: int64

In [117]:
df.groupby("department")["performance_score"].max()

department
Finance      4.9
HR           3.9
IT           4.3
Marketing    4.6
Sales        3.7
Name: performance_score, dtype: float64

In [120]:
df.groupby("department")["salary"].mean()
df.groupby("department")["salary"].max()
df.groupby("department")["salary"].count()

department
Finance      2
HR           2
IT           3
Marketing    2
Sales        1
Name: salary, dtype: int64

In [122]:
df.groupby("department")["salary"].agg(["min", "max", "mean"])

              min    max          mean
department
Finance     91000  95000  93000.000000
HR          70000  72000  71000.000000
IT          80000  88000  84333.333333
Marketing   76000  78000  77000.000000
Sales       67000  67000  67000.000000

## Q. For each department, calculate average salary and average performance score.

In [124]:
df.groupby("department").agg({
    "salary": "mean",
    "performance_score": "mean"
})

                  salary  performance_score
department
Finance     93000.000000               4.85
HR          71000.000000               3.85
IT          84333.333333               4.20
Marketing   77000.000000               4.50
Sales       67000.000000               3.70

In [133]:
new1 = df.sort_values("salary", ascending=False)[["name", "salary"]].head(3)
new1

          name  salary
1   Mary Smith   95000
5  Linda Perez   91000
7    Sara Khan   88000

In [134]:
df.sort_values("salary", ascending=False)[["name", "salary"]].iloc[:3]

          name  salary
1   Mary Smith   95000
5  Linda Perez   91000
7    Sara Khan   88000

## Find the 2 highest-paid employees from the IT department. Return name, department, and salary.

filter department == IT
        ↓
sort salary descending
        ↓
take top 2
        ↓
select required columns

In [147]:
# df[(df.sort_values("salary", ascending=False)) & (df["departnment" == "IT"])][["name", "department", "salary"]]

df[df["department"] == "IT"].sort_values("salary", ascending=False)[["name", "department", "salary"]].iloc[:2]

        name department  salary
7  Sara Khan         IT   88000
0   John Doe         IT   85000

## Q3 — Now GroupBy + Sort 🔥

Find the average salary of each department and show the departments from highest average salary to lowest.

In [154]:
df.groupby("department")["salary"].mean().sort_values(ascending=False)

department
Finance      93000.000000
IT           84333.333333
Marketing    77000.000000
HR           71000.000000
Sales        67000.000000
Name: salary, dtype: float64