In [1]:
print("hello")

hello

# pandas
* series
* Dataframe

In [4]:
import pandas as pd
s = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
data = {"name":["a", "b", "c"], "marks":[1,2,3]}
df = pd.DataFrame(data)
df

  name  marks
0    a      1
1    b      2
2    c      3

In [ ]:
import pandas as pd

# Sample data
data = {
    "id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["John Doe", "Mary Smith", "Alex Johnson", "Bob Lee", "Eve Adams", 
             "Linda Perez", "Tom Harris", "Sara Khan", "Chris Brown", "Nina Patel"],
    "department": ["IT", "Finance", "HR", "IT", "Marketing", 
                   "Finance", "Sales", "IT", "HR", "Marketing"],
    "gender": ["M", "F", "M", "M", "F", "F", "M", "F", "M", "F"],
    "salary": [85000, 95000, 70000, 80000, 78000, 91000, 67000, 88000, 72000, 76000],
    "joining_date": ["2020-06-15", "2019-08-10", "2021-02-01", "2022-03-20",
                     "2020-11-05", "2018-12-25", "2021-09-10", "2019-04-18",
                     "2022-05-25", "2020-02-12"],
    "performance_score": [4.3, 4.8, 3.9, 4.1, 4.6, 4.9, 3.7, 4.2, 3.8, 4.4],
    "is_active": [True, True, False, True, True, True, True, False, True, True]
}

df = pd.DataFrame(data)
csv_path = "employee.csv"
excel_path = "employee.xlsx"


df.to_csv(csv_path, index=False)
df.to_excel(excel_path, index=False, sheet_name="Employee")

In [13]:
! pip install openpyxl

/bin/bash: /home/ashwin/2025/study/interview_2025/.venv/bin/pip: /home/ashwin/study/interview_2025/.venv/bin/python3.13: bad interpreter: Permission denied

In [17]:
import pandas as pd
df = pd.read_csv("employee.csv")
df.head(10)

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [18]:
import pandas as pd
df = pd.read_csv("employee.csv")
df.tail(10)

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [19]:
df.describe()

             id        salary  performance_score
count  10.00000     10.000000          10.000000
mean    5.50000  80200.000000           4.270000
std     3.02765   9354.737362           0.411096
min     1.00000  67000.000000           3.700000
25%     3.25000  73000.000000           3.950000
50%     5.50000  79000.000000           4.250000
75%     7.75000  87250.000000           4.550000
max    10.00000  95000.000000           4.900000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     object
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     int64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     float64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 702.0+ bytes

## data selection

In [21]:
df["id"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [22]:
type(df["id"])

pandas.core.series.Series

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     object
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     int64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     float64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 702.0+ bytes

In [26]:
df[["id", "name"]]

   id          name
0   1      John Doe
1   2    Mary Smith
2   3  Alex Johnson
3   4       Bob Lee
4   5     Eve Adams
5   6   Linda Perez
6   7    Tom Harris
7   8     Sara Khan
8   9   Chris Brown
9  10    Nina Patel

In [27]:
df.iloc[0]

id                            1
name                   John Doe
department                   IT
gender                        M
salary                    85000
joining_date         2020-06-15
performance_score           4.3
is_active                  True
Name: 0, dtype: object

In [ ]:
import pandas as pd
df2 = pd.read_csv("data.csv")
df2.head(5)

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000.0,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,NaN,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000.0,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000.0,2022-03-20,NaN,True
4,5,Eve Adams,Marketing,F,78000.0,2020-11-05,4.6,True

In [30]:
df2.dropna()

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000.0,2020-06-15,4.3,True
2,3,Alex Johnson,HR,M,70000.0,2021-02-01,3.9,False
4,5,Eve Adams,Marketing,F,78000.0,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000.0,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000.0,2021-09-10,3.7,True
8,9,Chris Brown,HR,M,72000.0,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000.0,2020-02-12,4.4,True

In [33]:
df2.fillna(0)
df2.fillna(0, inplace=True)

In [34]:
df2

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000.0,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,0.0,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000.0,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000.0,2022-03-20,0.0,True
4,5,Eve Adams,Marketing,F,78000.0,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000.0,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000.0,2021-09-10,3.7,True
7,8,Sara Khan,0,F,88000.0,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000.0,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000.0,2020-02-12,4.4,True

In [1]:
df2.rename(columns={"name":"name1"})

NameError: name 'df2' is not defined

In [39]:
df2.describe()

             id        salary  performance_score
count  10.00000     10.000000          10.000000
mean    5.50000  70700.000000           3.860000
std     3.02765  26030.110769           1.415941
min     1.00000      0.000000           0.000000
25%     3.25000  70500.000000           3.825000
50%     5.50000  77000.000000           4.250000
75%     7.75000  83750.000000           4.550000
max    10.00000  91000.000000           4.900000

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     object
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     float64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     float64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 702.0+ bytes

In [44]:
df2['performance_score'] = df2['performance_score'].astype(int)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     object
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     float64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     int64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 702.0+ bytes

In [46]:
df2["name"] = df["name"].astype("string")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     string
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     float64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     int64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(3), string(1)
memory usage: 702.0+ bytes

In [47]:
len(df2)

10

In [48]:
df2["zeros"] = [0 for i in range(len(df2))]
df2

,id,name,department,gender,salary,joining_date,performance_score,is_active,zeros
0,1,John Doe,IT,M,85000.0,2020-06-15,4,True,0
1,2,Mary Smith,Finance,F,0.0,2019-08-10,4,True,0
2,3,Alex Johnson,HR,M,70000.0,2021-02-01,3,False,0
3,4,Bob Lee,IT,M,80000.0,2022-03-20,0,True,0
4,5,Eve Adams,Marketing,F,78000.0,2020-11-05,4,True,0
5,6,Linda Perez,Finance,F,91000.0,2018-12-25,4,True,0
6,7,Tom Harris,Sales,M,67000.0,2021-09-10,3,True,0
7,8,Sara Khan,0,F,88000.0,2019-04-18,4,False,0
8,9,Chris Brown,HR,M,72000.0,2022-05-25,3,True,0
9,10,Nina Patel,Marketing,F,76000.0,2020-02-12,4,True,0

In [52]:
def fx(a):
    return a+1


df2["zeros + 1"] = df["zeros"] .apply(fx(1))
df2

KeyError: 'zeros'

## Pandas for interview
https://www.youtube.com/watch?v=0T9qhK5wBqI

In [1]:

import pandas as pd
data = {"Name":['Ram', 'Shaym','Ghanshaym'],
        "Age":[10,20,30],
        "City":["Nagpur", "Mumbai", "Kanpur"]}

df = pd.DataFrame(data)
print(df)

        Name  Age    City
0        Ram   10  Nagpur
1      Shaym   20  Mumbai
2  Ghanshaym   30  Kanpur

In [2]:
df.to_csv("now.csv", index=False)

In [ ]:
df.to_excel("now.xlsx", index=False)

In [8]:
df = pd.read_csv("employee.csv")
print(df.tail(10))
df.info()

   id          name department gender  salary joining_date  performance_score  \
0   1      John Doe         IT      M   85000   2020-06-15                4.3
1   2    Mary Smith    Finance      F   95000   2019-08-10                4.8
2   3  Alex Johnson         HR      M   70000   2021-02-01                3.9
3   4       Bob Lee         IT      M   80000   2022-03-20                4.1
4   5     Eve Adams  Marketing      F   78000   2020-11-05                4.6
5   6   Linda Perez    Finance      F   91000   2018-12-25                4.9
6   7    Tom Harris      Sales      M   67000   2021-09-10                3.7
7   8     Sara Khan         IT      F   88000   2019-04-18                4.2
8   9   Chris Brown         HR      M   72000   2022-05-25                3.8
9  10    Nina Patel  Marketing      F   76000   2020-02-12                4.4

   is_active
0       True
1       True
2      False
3       True
4       True
5       True
6       True
7      False
8       True
9       True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10 non-null     int64
 1   name               10 non-null     object
 2   department         10 non-null     object
 3   gender             10 non-null     object
 4   salary             10 non-null     int64
 5   joining_date       10 non-null     object
 6   performance_score  10 non-null     float64
 7   is_active          10 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 702.0+ bytes

In [9]:
df.describe()

             id        salary  performance_score
count  10.00000     10.000000          10.000000
mean    5.50000  80200.000000           4.270000
std     3.02765   9354.737362           0.411096
min     1.00000  67000.000000           3.700000
25%     3.25000  73000.000000           3.950000
50%     5.50000  79000.000000           4.250000
75%     7.75000  87250.000000           4.550000
max    10.00000  95000.000000           4.900000

## for select data

In [11]:
print(df['id'])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [13]:
print(df[['id','salary']])

   id  salary
0   1   85000
1   2   95000
2   3   70000
3   4   80000
4   5   78000
5   6   91000
6   7   67000
7   8   88000
8   9   72000
9  10   76000

In [14]:
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [20]:
high_salary = df[df['salary'] > 80000]
print(high_salary)

   id         name department gender  salary joining_date  performance_score  \
0   1     John Doe         IT      M   85000   2020-06-15                4.3
1   2   Mary Smith    Finance      F   95000   2019-08-10                4.8
5   6  Linda Perez    Finance      F   91000   2018-12-25                4.9
7   8    Sara Khan         IT      F   88000   2019-04-18                4.2

   is_active
0       True
1       True
5       True
7      False

## Multi query

In [22]:
dept_salary = df[(df['department']== "IT") & (df['salary']>80000)]
print(dept_salary)

   id       name department gender  salary joining_date  performance_score  \
0   1   John Doe         IT      M   85000   2020-06-15                4.3
7   8  Sara Khan         IT      F   88000   2019-04-18                4.2

   is_active
0       True
7      False

In [24]:
dept_salary_or = df[(df['department']=='IT') | (df['salary'] > 80000)]
dept_salary_or

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False

## .loc

In [25]:
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [27]:
df.loc[0,'salary'] = 87000
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1.0,John Doe,IT,M,87000.0,2020-06-15,4.3,True
1,2.0,Mary Smith,Finance,F,95000.0,2019-08-10,4.8,True
2,3.0,Alex Johnson,HR,M,70000.0,2021-02-01,3.9,False
3,4.0,Bob Lee,IT,M,80000.0,2022-03-20,4.1,True
4,5.0,Eve Adams,Marketing,F,78000.0,2020-11-05,4.6,True
5,6.0,Linda Perez,Finance,F,91000.0,2018-12-25,4.9,True
6,7.0,Tom Harris,Sales,M,67000.0,2021-09-10,3.7,True
7,8.0,Sara Khan,IT,F,88000.0,2019-04-18,4.2,False
8,9.0,Chris Brown,HR,M,72000.0,2022-05-25,3.8,True
9,10.0,Nina Patel,Marketing,F,76000.0,2020-02-12,4.4,True
0,NaN,NaN,NaN,NaN,87000.0,NaN,NaN,NaN

In [15]:
import pandas as pd
df = pd.read_csv("employee.csv")
df[["department", "salary"]]
df.describe()
df.head(10)
df.tail(5)
df_and = df[(df["department"] == "IT") & (df["salary"] > 10000)]
print(df_and)
df_or = df[(df["department"] == "IT") | (df["salary"] > 10000)]
# print("df_or", df_or)

   id       name department gender  salary joining_date  performance_score  \
0   1   John Doe         IT      M   85000   2020-06-15                4.3
3   4    Bob Lee         IT      M   80000   2022-03-20                4.1
7   8  Sara Khan         IT      F   88000   2019-04-18                4.2

   is_active
0       True
3       True
7      False

In [17]:
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

## update in row single value

In [19]:
df.loc[3,"salary"] = 81000

In [20]:
df.loc[3, "salary"]

np.int64(81000)

## in a salary coloum update all values

In [ ]:
df["salary"] = df["salary"] *1.05
df

## Drop single or multiple coloums

In [ ]:
print(df)
df_new=df.drop(columns=["performance_score", "salary"], inplace=False)
df_new

## missing values in coloumn
* NaN = (Not a number)
* None = (for object data types)

In [29]:
df.isnull()
df.isnull().sum()

id                   0
name                 0
department           0
gender               0
salary               0
joining_date         0
performance_score    0
is_active            0
dtype: int64

## if missing data how to handle

In [ ]:
df.dropna(inplace=True)

## If dropna with coloum or row or fill na with some default value
df.fillna(0, inplace=True)

## we can fill with aveg or mean value 

df["performance_score"].fillna(df["performance_score"].mean(), inplace=True)

## for salary if anyone have NA
df["salary"].fillna(df["salary"].mean(), inplace=True)
df

## interpolation
* to fill Na value with estimated value , using linear, polynomial, time , quadratic, cubic interpolition
* preserve data integrity, smooth trends, avoid data loss
* interpolate()

In [ ]:
df.interpolate(method="linear", axis=0, inplace=True)

In [40]:
data = {"time":[1,2,3,4,5],
        "value":[10, None, 30, None, 50]}

In [ ]:
df = pd.DataFrame(data)
print(df)
df["value"] = df["value"].interpolate(method="linear")
df

## Sorting and aggregation

In [51]:
df = pd.read_csv("employee.csv")
df

,id,name,department,gender,salary,joining_date,performance_score,is_active
0,1,John Doe,IT,M,85000,2020-06-15,4.3,True
1,2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True
2,3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False
3,4,Bob Lee,IT,M,80000,2022-03-20,4.1,True
4,5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True
5,6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True
6,7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True
7,8,Sara Khan,IT,F,88000,2019-04-18,4.2,False
8,9,Chris Brown,HR,M,72000,2022-05-25,3.8,True
9,10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True

In [ ]:
df.sort_values(by="salary", ascending=True, inplace=True)
df.sort_values(by="name", ascending=False, inplace=True)
df

In [ ]:
df.sort_values(by=["name", "salary"], ascending=False,inplace=True)
df

## aggrecation : summary statastics

In [56]:
avg_salary = df["salary"].mean()
avg_salary

np.float64(80200.0)

## data group by in sql , same in pandas

In [58]:
group_by = df.groupby("department")["salary"].sum()
group_by

department
Finance      186000
HR           142000
IT           253000
Marketing    154000
Sales         67000
Name: salary, dtype: int64

### Revising start

In [ ]:
import pandas as pd
df = pd.read_csv("employee.csv")
df2=df[df["salary"] > 90000]
df2 = df[(df["salary"] > 60000) & (df["department"] == "IT")]
df.loc[0,"salary"] = 87000
df["salary"] = df["salary"] * 1.20
df_new = df.drop(columns=["name","department"], inplace=False)
df.dropna(inplace=True)
df.fillna(0, inplace=True)
df["salary"].fillna(df["salary"].mean(),inplace=True)
## interpolation
df.interpolate(method="linear",axis=0, inplace=True)

In [ ]:
data = {"time":[1,2,3,4,5],
        "value":[10, None, 30, None, 50]}
df = pd.DataFrame(data)
# df.interpolate(method="linear", axis=0)
df["value"]=df["value"].interpolate(method="linear")
df

In [34]:
## sorting and aggreation
df = pd.read_csv("employee.csv")
df.sort_values(by="salary", ascending=False, inplace=True)
df.sort_values(by="name", ascending=True, inplace=True)
df.sort_values(by=["name", "salary"], ascending=[True, True], inplace=True)
## aggrigation
av_salary = df["salary"].mean()
av_salary
## grop by like sql
gr = df.groupby("department")["salary"].sum()
gr

department
Finance      186000
HR           142000
IT           253000
Marketing    154000
Sales         67000
Name: salary, dtype: int64

## Revising End

## aggregation : Group by
* sum(), mean(), count(), min(), max()

In [10]:
import pandas as pd 
df = pd.read_csv("employee.csv")
df_g=df.groupby("department")["salary"].sum()
# df_g = df.groupby(["department", "name"])["salary"].sum()
df_g
df_g =df[df["salary"] > 10000].groupby("department")
df_g

## mearging and join

In [ ]:
import pandas as pd

customer = {'customerid':[1,2,3],
            'name':['ramesh', 'suresh', 'manish']}
order = {'customerid':[1,2,4],
         'orderamt':[210, 230, 250]}
df_cust = pd.DataFrame(customer)
df_order = pd.DataFrame(order)
# print(df_cust)
# print(df_order)
## inner join
df_inner = pd.merge(df_cust, df_order, on='customerid', how="inner")

## outer join
df_outer = pd.merge(df_cust, df_order, on="customerid", how="outer")
df_outer

## left join
df_left = pd.merge(df_cust, df_order, on="customerid", how="left")
df_left
## right join
df_right = pd.merge(df_cust, df_order, on="customerid", how="right")
df_right

## cross
# df_cross = pd.merge(df_cust, df_order, on="custmerid", how="cross")
# df_cross

MergeError: Can not pass on, right_on, left_on or set right_index=True or left_index=True

## concatinate
* vertically (row-wise)
* horizontally (colomn-wise)

In [53]:
import pandas as pd

customer1 = {'customerid':[1,2,3],
            'name':['ramesh', 'suresh', 'manish']}
customer2 = {'customerid':[4,5,6],
            'name':['mangesh', 'sachin', 'ankit']}
df_cust1 = pd.DataFrame(customer1)
df_cust2 = pd.DataFrame(customer2)

## concatinate vertically means row wise here axis is 0

df_concat=pd.concat([df_cust1, df_cust2], ignore_index=True)
df_concat

## concatinate horizontally means coloum wise here axis is 1
df_concat_hori =pd.concat([df_cust1,df_cust2], axis=1, ignore_index=True)
df_concat_hori

   0       1  2        3
0  1  ramesh  4  mangesh
1  2  suresh  5   sachin
2  3  manish  6    ankit

## practicing large file with the help of genrator or pandas

In [ ]:
import pandas as pd

def read_line(filname):
    with open(filname, 'r') as file:
        for line in file:
            yield line
for line in read_line("now.csv"):
    print(line)

In [ ]:
## using genratoe for fized size chunk

def read_chunk(filename, chunk_size=1024*1024):
    with open(filename, 'rb') as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            yield chunk

for chunk in read_chunk("employee.csv"):
    print(chunk)

b'id,name,department,gender,salary,joining_date,performance_score,is_active\n1,John Doe,IT,M,85000,2020-06-15,4.3,True\n2,Mary Smith,Finance,F,95000,2019-08-10,4.8,True\n3,Alex Johnson,HR,M,70000,2021-02-01,3.9,False\n4,Bob Lee,IT,M,80000,2022-03-20,4.1,True\n5,Eve Adams,Marketing,F,78000,2020-11-05,4.6,True\n6,Linda Perez,Finance,F,91000,2018-12-25,4.9,True\n7,Tom Harris,Sales,M,67000,2021-09-10,3.7,True\n8,Sara Khan,IT,F,88000,2019-04-18,4.2,False\n9,Chris Brown,HR,M,72000,2022-05-25,3.8,True\n10,Nina Patel,Marketing,F,76000,2020-02-12,4.4,True\n'

In [ ]:
## genrator using csv module

import csv
def csv_reader(filename):
    with open(filename, newline="") as f:
        reader = csv.reader(f)
        for row in reader:
            yield row
for row in csv_reader("employee.csv"):
    print(row)

In [59]:
## using pandas
import pandas as pd

for chunk in pd.read_csv("employee.csv", chunksize=100000):
    print(chunk.head())
    print(chunk.shape)

   id          name department gender  salary joining_date  performance_score  \
0   1      John Doe         IT      M   85000   2020-06-15                4.3
1   2    Mary Smith    Finance      F   95000   2019-08-10                4.8
2   3  Alex Johnson         HR      M   70000   2021-02-01                3.9
3   4       Bob Lee         IT      M   80000   2022-03-20                4.1
4   5     Eve Adams  Marketing      F   78000   2020-11-05                4.6

   is_active
0       True
1       True
2      False
3       True
4       True
(10, 8)